// <auto-generated />
using System;
using Eternelle.Modules.Weddings.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eternelle.Modules.Weddings.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WeddingsDbContext))]
    [Migration("20260512180221_ConfigureGuestPhotos")]
    partial class ConfigureGuestPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wedding")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.CeremonyActs.CeremonyAct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("ActTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("act_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_ceremony_acts");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_ceremony_acts_wedding_id_display_order");

                    b.ToTable("ceremony_acts", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.DressCodeConfigs.DressCodeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_dress_code_configs");

                    b.HasIndex("WeddingId")
                        .IsUnique()
                        .HasDatabaseName("ix_dress_code_configs_wedding_id");

                    b.ToTable("dress_code_configs", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.EntourageGroups.EntourageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("GroupType")
                        .HasColumnType("integer")
                        .HasColumnName("group_type");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<int>("RenderAs")
                        .HasColumnType("integer")
                        .HasColumnName("render_as");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subtitle");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_entourage_groups");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_entourage_groups_wedding_id_display_order");

                    b.ToTable("entourage_groups", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.GalleryImages.GalleryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("height_px");

                    b.Property<string>("SrcUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("src_url");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("width_px");

                    b.HasKey("Id")
                        .HasName("pk_gallery_images");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_gallery_images_wedding_id_display_order");

                    b.ToTable("gallery_images", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.GiftOptions.GiftOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("integer")
                        .HasColumnName("display_mode");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<string>("QrImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("qr_image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_gift_options");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_gift_options_wedding_id_display_order");

                    b.ToTable("gift_options", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.GuestPhotos.GuestPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("height_px");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("SrcUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("src_url");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploaderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploader_name");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("width_px");

                    b.HasKey("Id")
                        .HasName("pk_guest_photos");

                    b.HasIndex("WeddingId", "UploadedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_guest_photos_wedding_uploaded");

                    b.HasIndex("WeddingId", "Status", "UploadedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_guest_photos_wedding_status_uploaded");

                    b.ToTable("guest_photos", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_reminders_wedding_id_display_order");

                    b.ToTable("reminders", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.StoryMoments.StoryMoment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateOnly?>("StoryDate")
                        .HasColumnType("date")
                        .HasColumnName("story_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_story_moments");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_story_moments_wedding_id_display_order_id");

                    b.ToTable("story_moments", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.VendorCredits.VendorCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("instagram_handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("uuid")
                        .HasColumnName("wedding_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_credits");

                    b.HasIndex("WeddingId", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_vendor_credits_wedding_id_display_order");

                    b.ToTable("vendor_credits", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.Weddings.Wedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hashtag")
                        .HasColumnType("text")
                        .HasColumnName("hashtag");

                    b.Property<int>("Plan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("plan");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeddingDate")
                        .HasColumnType("date")
                        .HasColumnName("wedding_date");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_tenant_id");

                    b.ToTable("profiles", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.DressCodeConfigs.DressCodeConfig", b =>
                {
                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.DressCodeConfigs.DressCodeColor", "Colors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ColorHex")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("color_hex");

                            b1.Property<string>("ColorName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("color_name");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("DressCodeConfigId")
                                .HasColumnType("uuid")
                                .HasColumnName("dress_code_config_id");

                            b1.HasKey("Id")
                                .HasName("pk_dress_code_colors");

                            b1.HasIndex("DressCodeConfigId", "DisplayOrder", "Id")
                                .HasDatabaseName("ix_dress_code_colors_dress_code_config_id_display_order");

                            b1.ToTable("dress_code_colors", "wedding", t =>
                                {
                                    t.HasCheckConstraint("ck_dress_code_colors_color_hex", "color_hex ~ '^#[0-9A-Fa-f]{3,8}$'");
                                });

                            b1.WithOwner()
                                .HasForeignKey("DressCodeConfigId")
                                .HasConstraintName("fk_dress_code_colors_dress_code_configs_dress_code_config_id");
                        });

                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.DressCodeConfigs.DressCodeImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("DressCodeConfigId")
                                .HasColumnType("uuid")
                                .HasColumnName("dress_code_config_id");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.HasKey("Id")
                                .HasName("pk_dress_code_images");

                            b1.HasIndex("DressCodeConfigId", "DisplayOrder", "Id")
                                .HasDatabaseName("ix_dress_code_images_dress_code_config_id_display_order");

                            b1.ToTable("dress_code_images", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("DressCodeConfigId")
                                .HasConstraintName("fk_dress_code_images_dress_code_configs_dress_code_config_id");
                        });

                    b.Navigation("Colors");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.EntourageGroups.EntourageGroup", b =>
                {
                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.EntourageGroups.EntourageCouple", "Couples", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uuid")
                                .HasColumnName("group_id");

                            b1.Property<Guid>("MemberAId")
                                .HasColumnType("uuid")
                                .HasColumnName("member_a_id");

                            b1.Property<Guid>("MemberBId")
                                .HasColumnType("uuid")
                                .HasColumnName("member_b_id");

                            b1.Property<string>("Note")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("note");

                            b1.HasKey("Id")
                                .HasName("pk_entourage_couples");

                            b1.HasIndex("MemberAId")
                                .HasDatabaseName("ix_entourage_couples_member_a");

                            b1.HasIndex("MemberBId")
                                .HasDatabaseName("ix_entourage_couples_member_b");

                            b1.HasIndex("GroupId", "MemberAId", "MemberBId")
                                .IsUnique()
                                .HasDatabaseName("ix_entourage_couples_group_member_pair");

                            b1.ToTable("entourage_couples", "wedding", t =>
                                {
                                    t.HasCheckConstraint("ck_entourage_couples_member_order", "member_a_id < member_b_id");
                                });

                            b1.WithOwner()
                                .HasForeignKey("GroupId")
                                .HasConstraintName("fk_entourage_couples_entourage_groups_group_id");
                        });

                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.EntourageGroups.EntourageMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uuid")
                                .HasColumnName("group_id");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.Property<string>("Message")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("message");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("role");

                            b1.Property<int?>("Seed")
                                .HasColumnType("integer")
                                .HasColumnName("seed");

                            b1.Property<Guid>("WeddingId")
                                .HasColumnType("uuid")
                                .HasColumnName("wedding_id");

                            b1.HasKey("Id")
                                .HasName("pk_entourage_members");

                            b1.HasIndex("GroupId")
                                .HasDatabaseName("ix_entourage_members_group_id");

                            b1.HasIndex("WeddingId")
                                .HasDatabaseName("ix_entourage_members_wedding_id");

                            b1.HasIndex("GroupId", "Id")
                                .IsUnique()
                                .HasDatabaseName("uq_entourage_members_group_id_id");

                            b1.ToTable("entourage_members", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("GroupId")
                                .HasConstraintName("fk_entourage_members_entourage_groups_group_id");
                        });

                    b.Navigation("Couples");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.Weddings.Wedding", b =>
                {
                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.Weddings.Partner", "Partners", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bio")
                                .HasColumnType("text")
                                .HasColumnName("bio");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<int>("PartnerNumber")
                                .HasColumnType("integer")
                                .HasColumnName("partner_number");

                            b1.Property<Guid>("WeddingId")
                                .HasColumnType("uuid")
                                .HasColumnName("wedding_id");

                            b1.HasKey("Id")
                                .HasName("pk_partners");

                            b1.HasIndex("WeddingId", "PartnerNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_partners_wedding_id_partner_number");

                            b1.ToTable("partners", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("WeddingId")
                                .HasConstraintName("fk_partners_profiles_wedding_id");
                        });

                    b.OwnsOne("Eternelle.Modules.Weddings.Domain.Weddings.SnapShareConfig", "SnapShare", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CtaText")
                                .HasColumnType("text")
                                .HasColumnName("cta_text");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean")
                                .HasColumnName("enabled");

                            b1.Property<string>("InstagramHandle")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("instagram_handle");

                            b1.Property<int>("ModerationMode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("moderation_mode");

                            b1.Property<Guid?>("UploadToken")
                                .HasColumnType("uuid")
                                .HasColumnName("upload_token");

                            b1.Property<bool>("UploaderNameRequired")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("uploader_name_required");

                            b1.Property<Guid>("WeddingId")
                                .HasColumnType("uuid")
                                .HasColumnName("wedding_id");

                            b1.HasKey("Id")
                                .HasName("pk_snap_share_configs");

                            b1.HasIndex("UploadToken")
                                .IsUnique()
                                .HasDatabaseName("ix_snap_share_configs_upload_token")
                                .HasFilter("upload_token IS NOT NULL");

                            b1.HasIndex("WeddingId")
                                .IsUnique()
                                .HasDatabaseName("ix_snap_share_configs_wedding_id");

                            b1.ToTable("snap_share_configs", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("WeddingId")
                                .HasConstraintName("fk_snap_share_configs_profiles_id");
                        });

                    b.Navigation("Partners");

                    b.Navigation("SnapShare");
                });
#pragma warning restore 612, 618
        }
    }
}
