// <auto-generated />
using System;
using Eternelle.Modules.Weddings.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eternelle.Modules.Weddings.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WeddingsDbContext))]
    [Migration("20260428024551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wedding")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "wedding");
                });

            modelBuilder.Entity("Eternelle.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.Weddings.Wedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hashtag")
                        .HasColumnType("text")
                        .HasColumnName("hashtag");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeddingDate")
                        .HasColumnType("date")
                        .HasColumnName("wedding_date");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_tenant_id");

                    b.ToTable("profiles", "wedding");
                });

            modelBuilder.Entity("Eternelle.Modules.Weddings.Domain.Weddings.Wedding", b =>
                {
                    b.OwnsMany("Eternelle.Modules.Weddings.Domain.Weddings.Partner", "Partners", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bio")
                                .HasColumnType("text")
                                .HasColumnName("bio");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("text")
                                .HasColumnName("image_url");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<int>("PartnerNumber")
                                .HasColumnType("integer")
                                .HasColumnName("partner_number");

                            b1.Property<Guid>("WeddingId")
                                .HasColumnType("uuid")
                                .HasColumnName("wedding_id");

                            b1.HasKey("Id")
                                .HasName("pk_partners");

                            b1.HasIndex("WeddingId", "PartnerNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_partners_wedding_id_partner_number");

                            b1.ToTable("partners", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("WeddingId")
                                .HasConstraintName("fk_partners_profiles_wedding_id");
                        });

                    b.OwnsOne("Eternelle.Modules.Weddings.Domain.Weddings.SnapShareConfig", "SnapShare", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CtaText")
                                .HasColumnType("text")
                                .HasColumnName("cta_text");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean")
                                .HasColumnName("enabled");

                            b1.Property<string>("InstagramHandle")
                                .HasColumnType("text")
                                .HasColumnName("instagram_handle");

                            b1.Property<Guid>("WeddingId")
                                .HasColumnType("uuid")
                                .HasColumnName("wedding_id");

                            b1.HasKey("Id")
                                .HasName("pk_snap_share_configs");

                            b1.HasIndex("WeddingId")
                                .IsUnique()
                                .HasDatabaseName("ix_snap_share_configs_wedding_id");

                            b1.ToTable("snap_share_configs", "wedding");

                            b1.WithOwner()
                                .HasForeignKey("WeddingId")
                                .HasConstraintName("fk_snap_share_configs_profiles_id");
                        });

                    b.Navigation("Partners");

                    b.Navigation("SnapShare");
                });
#pragma warning restore 612, 618
        }
    }
}
