// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Eternelle.Modules.Weddings.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddWeddingAggregates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "wedding");

            migrationBuilder.CreateTable(
                name: "ceremony_acts",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    icon = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    act_time = table.Column<TimeOnly>(type: "time without time zone", nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ceremony_acts", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "dress_code_configs",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    description = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_dress_code_configs", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "entourage_groups",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    label = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    subtitle = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    group_type = table.Column<int>(type: "integer", nullable: true),
                    render_as = table.Column<int>(type: "integer", nullable: false),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_entourage_groups", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "gallery_images",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    src_url = table.Column<string>(type: "text", nullable: false),
                    alt_text = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    width_px = table.Column<int>(type: "integer", nullable: true),
                    height_px = table.Column<int>(type: "integer", nullable: true),
                    caption = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_gallery_images", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "gift_options",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    display_mode = table.Column<int>(type: "integer", nullable: false),
                    link_url = table.Column<string>(type: "text", nullable: true),
                    image_url = table.Column<string>(type: "text", nullable: true),
                    qr_image_url = table.Column<string>(type: "text", nullable: true),
                    account_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    account_number = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    account_type = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_gift_options", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "guest_photos",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    src_url = table.Column<string>(type: "text", nullable: false),
                    thumbnail_url = table.Column<string>(type: "text", nullable: true),
                    width_px = table.Column<int>(type: "integer", nullable: true),
                    height_px = table.Column<int>(type: "integer", nullable: true),
                    uploader_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    status = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    uploaded_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    reviewed_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_photos", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "inbox_message_consumers",
                schema: "wedding",
                columns: table => new
                {
                    inbox_message_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inbox_message_consumers", x => new { x.inbox_message_id, x.name });
                });

            migrationBuilder.CreateTable(
                name: "inbox_messages",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<string>(type: "text", nullable: false),
                    content = table.Column<string>(type: "jsonb", maxLength: 2000, nullable: false),
                    occurred_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    processed_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    error = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inbox_messages", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "outbox_message_consumers",
                schema: "wedding",
                columns: table => new
                {
                    outbox_message_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_outbox_message_consumers", x => new { x.outbox_message_id, x.name });
                });

            migrationBuilder.CreateTable(
                name: "outbox_messages",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<string>(type: "text", nullable: false),
                    content = table.Column<string>(type: "jsonb", maxLength: 2000, nullable: false),
                    occurred_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    processed_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    error = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_outbox_messages", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "profiles",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    schema_version = table.Column<int>(type: "integer", nullable: false),
                    wedding_date = table.Column<DateOnly>(type: "date", nullable: false),
                    hashtag = table.Column<string>(type: "text", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_profiles", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "reminders",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    icon = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    body = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_reminders", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "story_moments",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    story_date = table.Column<DateOnly>(type: "date", nullable: true),
                    description = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                    image_url = table.Column<string>(type: "text", nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_story_moments", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "vendor_credits",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    role = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    website_url = table.Column<string>(type: "text", nullable: true),
                    image_url = table.Column<string>(type: "text", nullable: true),
                    instagram_handle = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_vendor_credits", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "dress_code_colors",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    dress_code_config_id = table.Column<Guid>(type: "uuid", nullable: false),
                    color_hex = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    color_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_dress_code_colors", x => x.id);
                    table.CheckConstraint("ck_dress_code_colors_color_hex", "color_hex ~ '^#[0-9A-Fa-f]{3,8}$'");
                    table.ForeignKey(
                        name: "fk_dress_code_colors_dress_code_configs_dress_code_config_id",
                        column: x => x.dress_code_config_id,
                        principalSchema: "wedding",
                        principalTable: "dress_code_configs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "dress_code_images",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    dress_code_config_id = table.Column<Guid>(type: "uuid", nullable: false),
                    image_url = table.Column<string>(type: "text", nullable: false),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_dress_code_images", x => x.id);
                    table.ForeignKey(
                        name: "fk_dress_code_images_dress_code_configs_dress_code_config_id",
                        column: x => x.dress_code_config_id,
                        principalSchema: "wedding",
                        principalTable: "dress_code_configs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "entourage_couples",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    member_a_id = table.Column<Guid>(type: "uuid", nullable: false),
                    member_b_id = table.Column<Guid>(type: "uuid", nullable: false),
                    note = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_entourage_couples", x => x.id);
                    table.CheckConstraint("ck_entourage_couples_member_order", "member_a_id < member_b_id");
                    table.ForeignKey(
                        name: "fk_entourage_couples_entourage_groups_group_id",
                        column: x => x.group_id,
                        principalSchema: "wedding",
                        principalTable: "entourage_groups",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "entourage_members",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    group_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    role = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    image_url = table.Column<string>(type: "text", nullable: true),
                    message = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    seed = table.Column<int>(type: "integer", nullable: true),
                    display_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_entourage_members", x => x.id);
                    table.ForeignKey(
                        name: "fk_entourage_members_entourage_groups_group_id",
                        column: x => x.group_id,
                        principalSchema: "wedding",
                        principalTable: "entourage_groups",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "partners",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    partner_number = table.Column<int>(type: "integer", nullable: false),
                    first_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    last_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    bio = table.Column<string>(type: "text", nullable: true),
                    image_url = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_partners", x => x.id);
                    table.ForeignKey(
                        name: "fk_partners_profiles_wedding_id",
                        column: x => x.wedding_id,
                        principalSchema: "wedding",
                        principalTable: "profiles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "snap_share_configs",
                schema: "wedding",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    wedding_id = table.Column<Guid>(type: "uuid", nullable: false),
                    instagram_handle = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    cta_text = table.Column<string>(type: "text", nullable: true),
                    enabled = table.Column<bool>(type: "boolean", nullable: false),
                    upload_token = table.Column<Guid>(type: "uuid", nullable: true),
                    moderation_mode = table.Column<int>(type: "integer", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_snap_share_configs", x => x.id);
                    table.ForeignKey(
                        name: "fk_snap_share_configs_profiles_id",
                        column: x => x.wedding_id,
                        principalSchema: "wedding",
                        principalTable: "profiles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_ceremony_acts_wedding_id_display_order",
                schema: "wedding",
                table: "ceremony_acts",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_dress_code_colors_dress_code_config_id_display_order",
                schema: "wedding",
                table: "dress_code_colors",
                columns: new[] { "dress_code_config_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_dress_code_configs_wedding_id",
                schema: "wedding",
                table: "dress_code_configs",
                column: "wedding_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_dress_code_images_dress_code_config_id_display_order",
                schema: "wedding",
                table: "dress_code_images",
                columns: new[] { "dress_code_config_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_entourage_couples_group_member_pair",
                schema: "wedding",
                table: "entourage_couples",
                columns: new[] { "group_id", "member_a_id", "member_b_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_entourage_couples_member_a",
                schema: "wedding",
                table: "entourage_couples",
                column: "member_a_id");

            migrationBuilder.CreateIndex(
                name: "ix_entourage_couples_member_b",
                schema: "wedding",
                table: "entourage_couples",
                column: "member_b_id");

            migrationBuilder.CreateIndex(
                name: "ix_entourage_groups_wedding_id_display_order",
                schema: "wedding",
                table: "entourage_groups",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_entourage_members_group_id",
                schema: "wedding",
                table: "entourage_members",
                column: "group_id");

            migrationBuilder.CreateIndex(
                name: "ix_entourage_members_wedding_id",
                schema: "wedding",
                table: "entourage_members",
                column: "wedding_id");

            migrationBuilder.CreateIndex(
                name: "uq_entourage_members_group_id_id",
                schema: "wedding",
                table: "entourage_members",
                columns: new[] { "group_id", "id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_gallery_images_wedding_id_display_order",
                schema: "wedding",
                table: "gallery_images",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_gift_options_wedding_id_display_order",
                schema: "wedding",
                table: "gift_options",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "idx_guest_photos_wedding_status_uploaded",
                schema: "wedding",
                table: "guest_photos",
                columns: new[] { "wedding_id", "status", "uploaded_at" },
                descending: new[] { false, false, true });

            migrationBuilder.CreateIndex(
                name: "idx_guest_photos_wedding_uploaded",
                schema: "wedding",
                table: "guest_photos",
                columns: new[] { "wedding_id", "uploaded_at" },
                descending: new[] { false, true });

            migrationBuilder.CreateIndex(
                name: "ix_partners_wedding_id_partner_number",
                schema: "wedding",
                table: "partners",
                columns: new[] { "wedding_id", "partner_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_profiles_tenant_id",
                schema: "wedding",
                table: "profiles",
                column: "tenant_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_reminders_wedding_id_display_order",
                schema: "wedding",
                table: "reminders",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_snap_share_configs_upload_token",
                schema: "wedding",
                table: "snap_share_configs",
                column: "upload_token",
                unique: true,
                filter: "upload_token IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_snap_share_configs_wedding_id",
                schema: "wedding",
                table: "snap_share_configs",
                column: "wedding_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_story_moments_wedding_id_display_order_id",
                schema: "wedding",
                table: "story_moments",
                columns: new[] { "wedding_id", "display_order", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_vendor_credits_wedding_id_display_order",
                schema: "wedding",
                table: "vendor_credits",
                columns: new[] { "wedding_id", "display_order", "id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ceremony_acts",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "dress_code_colors",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "dress_code_images",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "entourage_couples",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "entourage_members",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "gallery_images",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "gift_options",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "guest_photos",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "inbox_message_consumers",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "inbox_messages",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "outbox_message_consumers",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "outbox_messages",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "partners",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "reminders",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "snap_share_configs",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "story_moments",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "vendor_credits",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "dress_code_configs",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "entourage_groups",
                schema: "wedding");

            migrationBuilder.DropTable(
                name: "profiles",
                schema: "wedding");
        }
    }
}
