// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Eternelle.Modules.Weddings.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class ConfigureGuestPhotos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "uploader_name_required",
                schema: "wedding",
                table: "snap_share_configs",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "plan",
                schema: "wedding",
                table: "profiles",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "uploader_name_required",
                schema: "wedding",
                table: "snap_share_configs");

            migrationBuilder.DropColumn(
                name: "plan",
                schema: "wedding",
                table: "profiles");
        }
    }
}
